#!/bin/bash

set -e

source /etc/os-release

build()
{
  podman run --privileged --rm -v /opt:/opt quay.io/skateman/atomic-zfs:${VERSION_ID}
  OLD_IMAGES=$(podman images --format "{{.Repository}}:{{.Tag}}" | grep "quay\.io\/skateman\/atomic-zfs" | grep -v "\:${VERSION_ID}$")
  [[ -z "$OLD_IMAGES" ]] && podman rmi $OLD_IMAGES
}

case "$1" in
  load)
    set +e
    if modprobe -n -d /opt/atomic-zfs zfs; then
      set -e
      modprobe -d /opt/atomic-zfs zfs
    else
      set -e
      build
      modprobe -d /opt/atomic-zfs zfs
    fi
  ;;

  unload)
    rmmod zfs
  ;;

  reload)
    rmmod zfs
    build
    modprobe -d /opt/atomic-zfs zfs
  ;;

esac

set +e
