---
name: RPM build in Fedora Copr
on:
  # Build only on pushes into main branch.
  push:
    branches: [main]

jobs:
  build:
    name: Submit a build from Fedora container
    # Run in Fedora container on Ubuntu VM (no direct Fedora support)
    container: fedora:latest
    runs-on: ubuntu-latest

    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v1

      - name: Set the API credentials for copr-cli
        env:
          API_TOKEN_CONTENT: ${{ secrets.COPR_API_TOKEN }}
          API_LOGIN_CONTENT: ${{ secrets.COPR_API_LOGIN }}
        run: |
          mkdir -p "$HOME/.config"
          echo "[copr-cli]"                                    > "$HOME/.config/copr"
          echo "login = ${API_LOGIN_CONTENT}"                 >> "$HOME/.config/copr"
          echo "username = skateman"                          >> "$HOME/.config/copr"
          echo "token = ${API_TOKEN_CONTENT}"                 >> "$HOME/.config/copr"
          echo "copr_url = https://copr.fedorainfracloud.org" >> "$HOME/.config/copr"

      - name: Install tooling for source RPM build
        run: |
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install copr-cli

      - name: Build the source RPM
        run: |
          rm -f *.src.rpm ;          \
          rpmbuild                   \
             --define "_sourcedir `pwd`" \
             --define "_rpmdir    `pwd`" \
             --define "_builddir  `pwd`" \
             --define "_specdir   `pwd`" \
             --define "_srcrpmdir `pwd`" \
               -bs *.spec

      - name: Submit the build by uploading the source RPM
        run: copr build skateman/atomic-zfs *.src.rpm
